site_name: OPDX Protocol Specification
site_url: https://spec.opdx.org
site_description: The OPDX Specification is a set of standards and guidelines for the Open Profile Data Exchange (OPDX) Protocol.
repo_url: https://github.com/opdxorg/spec
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  logo: assets/icon-light.png
  favicon: assets/icon-accent.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: opdx
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Overview: overview.md
  - API Specification:
      - Introduction: api/introduction.md
      - OPDX API Reference: api/reference.md
      - Security Considerations: api/security.md
  - FAQ: faq.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - privacy
  - search

extra:
  generator: false
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Open Profile Data Exchange (OPDX) Protocol. All rights reserved.
